# Default values for tile38.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: tile38/tile38
  tag: 1.12.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9851

leader:
  replicaCount: 1
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    annotations: {}
    existingClaim: ""
    mountPath: /data
    size: 2Gi
    # storageClass: ""
    subPath: ""
  prometheus:
    enabled: true
    port: 4321
    listenAddr: 0.0.0.0
    datadog:
      enabled: true

follower:
  replicaCount: 1
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  persistentVolume:
    enabled: false
  prometheus:
    enabled: true
    port: 4321
    listenAddr: 0.0.0.0
    datadog:
      enabled: true

aofshrink_job:
  enabled: true
  schedule: "0,30 * * * *"
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: []
  