apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tile38.fullname" . }}-follower
  labels:
    app: {{ template "tile38.name" . }}
    chart: {{ template "tile38.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: follower
data:
  config: |
    {
            "logconfig": {
                "level": "info",
                "encoding": "json",
                "outputPaths": [
                    "stdout"
                ],
                "errorOutputPaths": [
                    "stderr"
                ],
                "encoderConfig": {
                    "messageKey": "message",
                    "levelKey": "level",
                    "levelEncoder": "lowercase",
                    "timeKey": "timestamp",
                    "timeEncoder": "ISO8601"
                }
            }
          }
