{{- if .Values.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: >-
      {{ .Values.serviceAccount }}
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"iam.gke.io/gcp-service-account":"{{ .Values.serviceAccount }}"},"labels":{"app":"{{ template "tile38.name" . }}","argocd.argoproj.io/instance":"{{ template "tile38.name" . }}"},"name":"{{ template "tile38.name" . }}-ksa","namespace":"tile38"}}
  labels:
    app: {{ template "tile38.name" . }}
    argocd.argoproj.io/instance: {{ template "tile38.name" . }}
  name: geofence-feed-indexer-ksa
  namespace: tile38
{{- end }}