{{- if and .Values.serviceAccount .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: >-
      {{ .Values.serviceAccount.email }}
  labels:
    app: {{ template "tile38.name" . }}
    argocd.argoproj.io/instance: {{ template "tile38.name" . }}
    chart: {{ template "tile38.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.serviceAccount.name }}
  namespace: tile38
{{- end }}
